from . import ir_attachment
from . import website
from . import product_label
from . import product_label_line
from . import product_template
from . import product_attribute
from . import product_public_category
from . import website_menu
from . import product_brand_ept
from . import slider
from . import slider_filter
from . import slider_styles
from . import proudct_pricelist
from . import res_config
from . import product_tab_line
